version: '2.1'
services:
    mysql:
        image: mariadb:latest
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password_key
        ports:
            - "3306:3306"
        networks:
            - my_network

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - my_network

networks:
    my_network:
        external: true
